---
name: cmpsc-100-week-1-variables
break: true
indent: 4
---

activities/analog/writing/reflection.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountFileParagraphs --count 4

activities/digital/digital-0-variables.ipynb:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    
activities/digital/digital-0-variables.py:
    MatchFileFragment --fragment "input(" --count 1 --exact
    MatchFileFragment --fragment "int(" --count 1
    MatchFileFragment --fragment "working_number =" --count 1
    MatchFileFragment --fragment "-" --count 1
    MatchFileFragment --fragment "/=" --count 1
    MatchFileFragment --fragment "+=" --count 1
    MatchFileFragment --fragment "*=" --count 1
    MatchFileFragment --fragment "original_number =" --count 1

CountCommits --count 5
MatchCommandFragment --command "python activities/digital/digital-0-variables.py < activities/digital/.case" --fragment "8" --count 1 --exact